### Registro de usuario (Signup)
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "name": "Ulises2",
    "email": "Ulises2@example.com",
    "password": "contraseña123",
    "password_confirmation": "contraseña123"
}

### Iniciar sesión de usuario (Login)
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "email": "Ulises2@example.com",
    "password": "contraseña123"
}



### Obtener información del usuario autenticado (Get User)
GET http://127.0.0.1:8000/api/user
Authorization: Bearer 9|o4iJveIkwMRpQ4X8OftG30gvF9MFq1fTB8Yn1oMY000080cb


### Cerrar sesión (Logout)
POST http://127.0.0.1:8000/api/logout
Authorization: Bearer 4|jvaaFNxA8hO5ve2VuucmSQ7WkmFJQ56wxOEidH7dfbdf5bf0


### búsqueda

GET http://127.0.0.1:8000/api/search?query=Nuevo Usuario
Authorization: Bearer 9|o4iJveIkwMRpQ4X8OftG30gvF9MFq1fTB8Yn1oMY000080cb

### ### Cerrar sesión (Logout a todo)

POST http://127.0.0.1:8000/api/logout-all
Authorization: Bearer 10|XdWkNyVJuaVhS371zeuZPCY2K1jZT0ANyGN096Kg6daf62b2
Content-Type: application/json


### ### para refrescar el token
POST http://127.0.0.1:8000/api/refresh-token
Authorization: Bearer 9|o4iJveIkwMRpQ4X8OftG30gvF9MFq1fTB8Yn1oMY000080cb
Content-Type: application/json


### Eliminar cuenta del usuario
DELETE http://127.0.0.1:8000/api/user/delete
Authorization: Bearer 11|vpRdZ1HcDXgmaQiqPCeYhpnghoLh8pqMlvIhDa3Y9cc15841
Content-Type: application/json

{
    "password": "contraseña123"
}
