### Registro de usuario (Signup)
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "name": "Nuevo Usuario",
    "email": "usuario@example.com",
    "password": "contraseña123",
    "password_confirmation": "contraseña123"
}

### Iniciar sesión de usuario (Login)
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "email": "usuario@example.com",
    "password": "contraseña123"
}



### Obtener información del usuario autenticado (Get User)
GET http://127.0.0.1:8000/api/user
Authorization: Bearer 3|lx8oObu85wiMMWzPefWQaBiGPDpO7PNwF0z20nzTbe5e9677


### Cerrar sesión (Logout)
POST http://127.0.0.1:8000/api/logout
Authorization: Bearer 2|E51d13Iq0VuOyRt2OOtYm9jQGVT4DvZz1whHg47Edd1d6e1f


### búsqueda

GET http://127.0.0.1:8000/api/search?query=Nuevo Usuario
Authorization: Bearer 7|GdRbhLQN2m7ALP1T6R7t0ak7kuiOzDN7x2UYd8Mm573f9d73

### ### Cerrar sesión (Logout a todo)

POST http://127.0.0.1:8000/api/logout-all
Authorization: Bearer 8|UFo40ePgyAkFus7g6htcFthdx98kTOis9tNZwpeL86eb5e74
Content-Type: application/json


### ### para refrescar el token
POST http://127.0.0.1:8000/api/refresh-token
Authorization: Bearer 7|GdRbhLQN2m7ALP1T6R7t0ak7kuiOzDN7x2UYd8Mm573f9d73
Content-Type: application/json
